### ISSUE TITLE
Icon and Fanart

### ISSUE THREAD

**Issue by enen92** [zosky/kodi.context.tags#1]
Hey @zosky,

Please add an icon and a fanart when possible and submit them as part of the next update to the repository. It does not look good either on kodi or on the addon website. You can read more about the sizes and format here:

http://kodi.wiki/view/Add-on_structure

Note that since krypton, those files should be specified in the assets tag of your addon.xml. See: http://kodi.wiki/view/Addon.xml

**Comment by zosky** [comment]
@enen92 thanks for the links. i have the files. i didn't realise krypton needed them referenced in the addon.xml. that's what i did in the [last pull](https://github.com/xbmc/repo-scripts/pull/481/commits/98e73520a9fa46cc38bf21b48ff7510c062e74d1). we cool now or you need anything else ?

**Comment by enen92** [comment]
lol, my apologies. 
I was checking which addons were having issues showing the icon on the website and since  the icon.png and the fanart were not on the root folder of the plugin (like before krypton) I assumed there were no images. In addition, totally forgot your last PR was indeed to fix this exact issue.
All is good. Basically, when the repository gets updated (update scripts run every few hours) the issue should be fixed in the website :)

Thanks and sorry for the time wasted
